# Generated by Django 3.1.6 on 2022-12-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20221209_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
